### Site Settings ###
title               : Yansı Evre Yüksel
icon                : /assets/favicon.ico
icon_size           : 32
description         : >-
                      The multi-disciplinary wizard
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : yansievre/yansievre.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
### Author Info ###
author:
  name              : Yansı Evre Yüksel
  images:
    - /assets/photos/p1.png
    - /assets/photos/pp2.png
    - /assets/photos/p3.png
    - /assets/photos/unikalumo.png
    - /assets/photos/p2.png
    - /assets/photos/pp1.png
    - /assets/photos/p5.png
    - /assets/photos/p6.png
  gradient-default: '#41474a'
  gradient-hover: 
    - '#91005d'
    - '#5e5e16'
    - '#184a59'
    - '#5e6e42'
# behance           : your_username
# dribbble          : your_username
  email             : yanevyuk@gmail.com
# facebook          : your_username
  github            : yansievre
# gitlab            : your_username
  instagram         : yanevyuk
# kaggle            : your_username
  linkedin          : yanevyuk
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : yanevyuk
  twitter           : yanevyuk
# vimeo             : your_username
  youtube           : channel/UCg5bsFnNtIZDVkuUp_SEX-Q
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: true
  username: yanevyuk
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
